import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        {children}
        <div className="absolute inset-0 -z-10 blur-3xl">
          <div className="animate-left absolute left-0 top-0 -z-50 h-[500px] w-[500px] rounded-full bg-gradient-to-t from-[#d175b542] to-[#183069]"></div>
          <div className="animate-right absolute bottom-0 delay-500 right-0 -z-50 h-[500px] w-[500px] rounded-full bg-gradient-to-l from-[#d175b542] to-[#183069]"></div>
        </div>
      </body>
    </html>
  );
}
